
const Pages = {
    PAGE_LOGIN: 'LOGIN/LOGIN',
    PAGE_LOGIN_CADASTRAR: 'LOGIN/CADASTRAR',
    PAGE_LOGIN_RECUPERAR_SENHA: 'LOGIN/RECUPERARSENHA',

    PAGE_PRODUTO: 'PRODUTO/PRODUTO',
    PAGE_CARDAPIO: 'CARDAPIO/CARDAPIO',
    PAGE_HOME: 'HOME',
    
    PAGE_CATEGORIA: 'CATEGORIA/CATEGORIA',
    PAGE_PARTIALS_MODAL_CATEGORIA: 'PARTIALS/MODALCATEGORIA',
    

    PAGE_CLIENTE: 'CLIENTE/CLIENTE',
    PAGE_MODAL_CLIENTE: 'CLIENTE/MODALCLIENTE',
    
    PAGE_FUNCIONARIO: 'FUNCIONARIO/FUNCIONARIO',
    PAGE_MODAL_FUNCIONARIO: 'FUNCIONARIO/MODALFUNCIONARIO',

    PAGE_MESA: 'MESA/MESA',
    PAGE_MODAL_MESA: 'MESA/MODALMESA',

    PAGE_PARTIALS_MODAL_DELETAR: 'PARTIALS/MODALDELETE',
    PAGE_PARTIALS_MODAL_PRODUTO: 'PARTIALS/MODALPRODUTO',

    PAGE_PARTIALS_MODAL_CARDAPIO: 'PARTIALS/CARDAPIO',
    
    PAGE_PARTIALS_MODAL_CARDAPIO: 'PARTIALS/CLIENTE',
}

module.exports = Pages;